### ISSUE TITLE
Add Vite 6 compatibility

### ISSUE THREAD

**Issue by luc122c** [f-lawe/vite-plugin-dts-bundle-generator#2]
Hi There! Thanks for the great tool! I have been using it with Vite 6 since it was released last month. It seems to work fine, since the API's are the same. However, I get a notice in the console becasue the package.json does not include `^6.0.0`. If you get chance, please could you look at including Vite 6 in the peer dependencies? Thank you :)

**Comment by f-lawe** [comment]
Hello!
Very good point. I'm not working on projects using Vite at the moment, I totally missed it. I ran some tests on my own and it seems to work fine indeed.
[2.0.6](https://www.npmjs.com/package/vite-plugin-dts-bundle-generator/v/2.0.6) has been pushed to npmjs 👍

**Comment by luc122c** [comment]
That's brilliant, thank you so much for the speedy response! <3
